db:
  container_name: wordpress-db
  build: db/
  ports:
    - 3306:3306

wordpress:
  container_name: wordpress-web
  build: wordpress/
  links:
    - db
  ports:
    - 8080:80
  volumes:
    - ./theme:/var/www/wordpress/wp-content/themes/custom
